### ISSUE TITLE
Missing folder

### ISSUE THREAD

**Issue by XLechter** [lxa9867/PaintSeg#1]
Hi authors, thanks for sharing the codes.

In PaintSeg.py L12:

sys.path.append('./mae')
import models_mae

There seems no this folder **mae**, could you kindly help me with this?

Thank you so much!

**Comment by lxa9867** [comment]
Hi, 

Sorry for the confusion. I think mae is not used in the released version. You may delete L12 for quick testing.

And if you want to try mae as the image projector, you can clone https://github.com/facebookresearch/mae and put it in the main directory.
