### ISSUE TITLE
about Δ- and Δ+

### ISSUE THREAD

**Issue by xuecheng990531** [lxa9867/PaintSeg#4]
Dear author, in the previous definition you took the results of the contrastive potential and ran them through kmeans to get the initial Mask. after that you rewrote a formula for Mt+1 for Δ- and Δ+, can you tell me the reason for doing this is because you only wanted to update the results at the boundaries of the Mask to do this?

**Comment by lxa9867** [comment]
Hi,

Yes, the purpose of using Δ is to constrain the updating region. We found only updating the boundary can make the AMCP process more stable.

**Comment by xuecheng990531** [comment]
Thanks for your answer, but I still have one thing to confirm. The comparison between the original and the painted image is done by calculating the difference in distance at each point to get a difference map, which is the phi-paint item you mentioned in your article, and then later adding the conditional random field （CRF） as well as the prompt item for the calculation. Finally the three total items mentioned above are summed to achieve the mask update by clustering right?
<img width="502" alt="截屏2024-05-02 23 16 47" src="https://github.com/lxa9867/PaintSeg/assets/41404131/e0b1ef9d-d4cb-4f02-aaf8-6bf1f81805dc">

**Comment by lxa9867** [comment]
Yes, you are correct. Please let me know if you have more questions.

**Comment by xuecheng990531** [comment]
thanks！I have no questions right now！

**Comment by lxa9867** [comment]
Sounds good. I will close this issue then.
