### ISSUE TITLE
contrastive potential convert to mask

### ISSUE THREAD

**Issue by li1999x** [lxa9867/PaintSeg#5]
Dear Author, 

Assuming that my contrastive potential is calculated using only the paint term, the process of obtaining the mask (assuming that the I step is being performed) has the false positive portion of the region filled with pixels with a smaller difference from the original image, and the target region replaced by the background pixels with a larger difference. By clustering the difference using kmeans, the original false positive region is reclassified as the background part because of the smaller difference, and the region with the larger difference is classified as the foreground part, which achieves the update of the initial Mask.

Do I understand correctly?

**Comment by lxa9867** [comment]
You are correct. Please note that the issue section aims to resolve the technical issues. I would encourage you to read and discuss the paper with your colleagues to verify your understanding. Thanks.
